USE IsMutant;

CREATE TABLE IF NOT EXISTS CONSULTASDNA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ISMUTANT BOOLEAN NOT NULL,
    DNA VARCHAR(255) NOT NULL
);


INSERT INTO CONSULTASDNA (ISMUTANT, DNA)
VALUES (TRUE, '"ATGTTA","CAGTGC","TTATGT","AGATGG","CCCCTA","TCACTG"');

SELECT COUNT( * ) FROM CONSULTASDNA WHERE ISMUTANT IS TRUE;
SELECT COUNT( * ) FROM CONSULTASDNA WHERE ISMUTANT IS FALSE;