service: lambda-ismutate

custom:
  defaultProyecto: "Ejercicio is mutate Consorcio"

  Proyecto: challengeCNS
  region: us-east-2
  stage: dev
  apiNamePrefix: dev

  userbd: 
  passbd: 

  awsSecretStoreArn: 
  database: 
  dbClusterOrInstanceArn: 

provider:
  name: aws
  runtime: python3.6
  apiKeys:
    - ismutate-key
  stackTags:
    Proyecto: ${self:custom.Proyecto}
  region: ${self:custom.region}
  environment:
    awsSecretStoreArn: ${self:custom.awsSecretStoreArn}
    database: ${self:custom.database}
    dbClusterOrInstanceArn: ${self:custom.dbClusterOrInstanceArn}

functions:
  ismutate:
    handler: handler.ismutate
    timeout: 30
    events:
      - http:
          path: ismutate
          method: post
          private: true
  statistic:
    handler: handler.statistic
    timeout: 30
    events:
      - http:
          path: statistic
          method: get
          private: true

resources:
  Resources:
    CreateClusterAurora:
      Type: AWS::RDS::DBCluster
      Properties:
        DatabaseName: isMutant
        DBClusterIdentifier: mi-serverless-clister-ismutant
        DeletionProtection: false
        EnableHttpEndpoint: true
        Engine: aurora
        EngineMode: serverless
        MasterUsername: ${self:custom.userbd}
        MasterUserPassword: ${self:custom.passbd}
        SourceRegion: ${self:custom.region}
